# Generated by Django 5.0.14 on 2026-06-10 14:25

import Exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_key',
            field=models.CharField(default=Exams.models.generate_short_key, editable=False, max_length=8, unique=True),
        ),
    ]
